name: MicrobiomePrime
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.19
  - biopython=1.83
  - pandas=2.0.3
  - pip=24.0
  - r-base=4.1.3
  - r-config=0.3.1
  - r-data.table=1.14.8
  - r-dplyr=1.1.2
  - r-ini=0.3.1
  - r-seqinr=4.2_30
  - r-stringr=1.5.0
  - r-tibble=3.2.1
  - r-tidyr=1.3.0